### ISSUE TITLE
Hoping to see official nightlies soon.

### ISSUE THREAD

**Issue by sarvesvara** [MoKee/android_device_xiaomi_leo#3]
OK, we have got an unofficial release. And it is 6.0.1 now.
Thanks for the wonderful update.
Hoping to see official nightlies soon.

**Comment by MisteRemix** [comment]
Great ROM, thanks for update,
Can you add DT2W feature ?

**Comment by sarvesvara** [comment]
That's kernel feature!!

**Comment by nian0114** [comment]
comming soon when bug is less

**Comment by sarvesvara** [comment]
> comming soon when bug is less

Thanks.

**Comment by sarvesvara** [comment]
Official nightlies & Releases are available for a while now.
